# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 20df1a45029dbeee6b0393788630aec1845cf6b88043ca6afb46790011f20742be1c66747468ca4f9d37508928bda83936a9f12a3ce2191fd5f51e94a23da78e

test:
  secret_key_base: 81c443c8d35c87a2e8bbaa5a96cb381975a9c0013fc8a48e144395cbd3d386feb55f73abe6956767aa191a3a76e8ed5a3b86025d01fc98730f58a6924da6c8b8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
